/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import gsap from 'gsap';
import {useGSAP} from '@gsap/react';
import {useRef, useState} from 'react';
import {Float, useGLTF, useTexture} from '@react-three/drei';

const Cube = ({...props}) => {
    const {scene} = useGLTF('models/rubiks_cube.glb');

    const cubeRef = useRef();
    const [hovered, setHovered] = useState(false);

    useGSAP(() => {

        const tl = gsap.timeline({
            repeat: -1,
            repeatDelay: 0.6
        });

        tl.to(cubeRef.current.rotation, {
            y: "+=" + Math.PI / 2,
            duration: 0.5
        });

        tl.to(cubeRef.current.rotation, {
            x: "+=" + Math.PI / 2,
            duration: 0.5
        });

        tl.to(cubeRef.current.rotation, {
            z: "+=" + Math.PI / 2,
            duration: 0.5
        });

    });

    return (
        <Float floatIntensity={2}>
            <group
                ref={cubeRef}
                position={[9, -4, 0]}
                rotation={[2.6, 0.8, -1.8]}
                scale={10}
                dispose={null}
                {...props}
                onPointerEnter={() => setHovered(true)}
                onPointerLeave={() => setHovered(false)}
            >
                <primitive object={scene}/>
            </group>
        </Float>
    );
};

useGLTF.preload('models/rubiks_cube.glb');

export default Cube;